// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mugpduprirakoigipnif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11Z3BkdXByaXJha29pZ2lwbmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODgyMDUsImV4cCI6MjA2NTQ2NDIwNX0.4wnXVyBKa0ymbUsUKHoCrKKzfAe727OD0g1ymAB4jgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);